# permissions for end users to view serviceclaims.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: serviceclaim-viewer-role
rules:
- apiGroups:
  - tsmgr.vmware.com
  resources:
  - serviceclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tsmgr.vmware.com
  resources:
  - serviceclaims/status
  verbs:
  - get
